import type { Direction, PixelMatrix } from './types.js';
import { SPRITE_W, SPRITE_H } from './types.js';

/**
 * Face overlays (eyes + mouth) per direction. Shared across all characters —
 * facial expression variation lives in the accessory layer (glasses, blush, etc).
 *
 * E/W is asymmetric: eye is on the character's right cheek from the viewer's
 * POV of "facing east". W is mirrored at atlas build time.
 */

function pad(row: string): string {
  if (row.length > SPRITE_W) {
    console.warn(`faces.ts: row width ${row.length} > ${SPRITE_W}, truncating — "${row}"`);
    return row.slice(0, SPRITE_W);
  }
  return row.length === SPRITE_W ? row : row + '.'.repeat(SPRITE_W - row.length);
}

function build(rows: Record<number, string>): PixelMatrix {
  const out: string[] = [];
  for (let y = 0; y < SPRITE_H; y++) {
    out.push(pad(rows[y] ?? '.'.repeat(SPRITE_W)));
  }
  return out;
}

const faceS = build({
  8:  '.........EE..EE.........',
  9:  '.........EE..EE.........',
  11: '...........MM...........',
});

/** Back view — no face features. */
const faceN = build({});

/** East-facing profile. Single eye near front of face, mouth pulled to right. */
const faceE = build({
  8:  '..............EE........',
  9:  '..............EE........',
  11: '.............MM.........',
});

/** West is generated by mirroring E at build time; placeholder for typing. */
const faceW = faceE;

export const FACES: Record<Direction, PixelMatrix> = {
  S: faceS,
  N: faceN,
  E: faceE,
  W: faceW,
};
